# Generated by Django 3.0.5 on 2021-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionApp', '0002_auto_20210502_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
