# Generated by Django 3.0.5 on 2021-05-03 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collectionApp', '0004_auto_20210502_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
