# Generated by Django 3.0.5 on 2021-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionApp', '0005_auto_20210503_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='collection_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
