# Generated by Django 3.2 on 2021-05-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectionApp', '0008_auto_20210503_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_uuid',
            new_name='uuid',
        ),
    ]
